### ISSUE TITLE
Could you fix the Youtube RSS feed?

### ISSUE THREAD

**Issue by Zzull** [magnars/parens-of-the-dead-s2#2]
Hello,

It's obviously not the best place to ask for such a request but I don't have an X account nor a Youtube account to be able to reach you there.

The [RSS feed of the Youtube channel](https://www.youtube.com/feeds/videos.xml?playlist_id=PLVfFIUHWy-aM9e9jW2Ir80EQq1jpjIQF9) has been broken for quite a while. I thought new entries were automatically generated by Youtube whenever new videos would be uploaded but it's apparently not the case.

Do you have the hand on it to try to fix it?

**Comment by magnars** [comment]
I can't fix YouTube's RSS feed, but maybe you can use the RSS feed from the website instead? http://parens-of-the-dead.com/atom.xml

**Comment by Zzull** [comment]
Per-fect
